### ISSUE TITLE
Virtual environment version

### ISSUE THREAD

**Issue by t3ch9** [GRrHaG/AutoUpdater#1]
Hello, thank you for the great script. Can you please provide a version of your script for freqtrade running in a virtual environment?

**Comment by GRrHaG** [comment]
Hi,
Yes i think it's possible : 
can you send me all command you use for :
- Activate virtual environment 
- Close virtual environment
- Start / Stop / Pull / Build freqtrade 
- Know the version of freqtrade

**Comment by t3ch9** [comment]
Hi, please let me know if I missed anything. Thank you.

Activate virtual environment:  conda activate freq1

Close virtual environment:  conda deactivate

Start freqtrade:  freqtrade trade --config configs/config_BOT1.json

Stop freqtrade:  pkill -f "/home/user/miniconda3/bin/python /home/user/miniconda3/bin/freqtrade trade --config configs/config_BOT1.json"

Pull freqtrade:  git pull

Build freqtrade:  pip install -U -r requirements.txt

Know the version of freqtrade:  freqtrade -V

**Comment by GRrHaG** [comment]
Hi , you can try v1.09
Update your config_autoupdater.json for add : 

		// INSTALLER : Enter "docker-compose" or "sudo docker-compose" or "custom"
		"INSTALLER": "custom",
		
		//For custom user only , enter your own command
		"CUSTOM_CMD_ACTIVATE_VE": "conda activate freq1", // Command for activate virtual environement 
		"CUSTOM_CMD_CLOSE_VE": "conda deactivate", // Command for close virtual environement
		"CUSTOM_CMD_VERSION": "freqtrade -V", // Command for show actual install version of Freqtrade 
		"CUSTOM_CMD_START": "freqtrade trade --config configs/config_BOT1.json", // Command for Start Freqtrade
		"CUSTOM_CMD_STOP": "pkill -f "/home/user/miniconda3/bin/python /home/user/miniconda3/bin/freqtrade trade --config configs/config_BOT1.json"", // Command for Stop Freqtrade
		"CUSTOM_CMD_PULL": "git pull", // Command for Pull Freqtrade
		"CUSTOM_CMD_BUILD": "pip install -U -r requirements.txt", // Command for Build Freqtrade

**Comment by t3ch9** [comment]
Thank you, will test. Cheers!

**Comment by t3ch9** [comment]
history_autoupdater.txt shows the following:

tail -f history_autoupdater.txt
2022-05-11 16:10 : ; ID=1 ; Strategy_Update=v11.0.700
2022-05-11 16:10 : ; ID=2 ; ERROR=Fail to Update Freqtrade v -V // Command for show actual install version of Freqtrade  to v2022.4.2

**Comment by GRrHaG** [comment]
The script seems to take comments into account

You can delete it 

	// INSTALLER : Enter "docker-compose" or "sudo docker-compose" or "custom"
	"INSTALLER": "custom",	
	//For custom user only , enter your own command
	"CUSTOM_CMD_ACTIVATE_VE": "conda activate freq1", 
	"CUSTOM_CMD_CLOSE_VE": "conda deactivate",
	"CUSTOM_CMD_VERSION": "freqtrade -V", 
	"CUSTOM_CMD_START": "freqtrade trade --config configs/config_BOT1.json",
	"CUSTOM_CMD_STOP": "pkill -f "/home/user/miniconda3/bin/python /home/user/miniconda3/bin/freqtrade trade --config configs/config_BOT1.json"",
	"CUSTOM_CMD_PULL": "git pull",
	"CUSTOM_CMD_BUILD": "pip install -U -r requirements.txt",

**Comment by t3ch9** [comment]
I removed all the comments. 

tail -f tools/history_autoupdater.txt
2022-05-11 19:35 : ; ID=1 ; Freqtrade_Update= -V
2022-05-11 19:40 : ; ID=2 ; ERROR=Fail to Update Freqtrade v -V to v2022.4.2
2022-05-11 19:45 : ; ID=3 ; ERROR=Fail to Update Freqtrade v -V to v2022.4.2
2022-05-11 19:50 : ; ID=4 ; ERROR=Fail to Update Freqtrade v -V to v2022.4.2

**Comment by GRrHaG** [comment]
I made a mistake in : "CUSTOM_CMD_CLOSE_VE": "conda deactivate", ==> "CUSTOM_CMD_CLOSE_VE": "conda desactivate",

For your problem I managed to reproduce it, the new version 1.10 fix it

**Comment by t3ch9** [comment]
After updating to v1.10, I am getting the following:

tail -f history_autoupdater.txt
2022-05-12 15:55 : ; ID=1 ; Strategy_Update=v11.0.700
2022-05-12 15:55 : ; ID=2 ; Freqtrade_Update= 2022.4.2

Is this correct? I guess I will have to wait until there is a new strategy and freqtrade update to see if all works properly.

**Comment by GRrHaG** [comment]
Yes it's good

**Comment by t3ch9** [comment]
New observation: 

tail -f history_autoupdater.txt
2022-05-12 15:55 : ; ID=1 ; Strategy_Update=v11.0.700
2022-05-12 15:55 : ; ID=2 ; Freqtrade_Update= 2022.4.2
2022-05-13 17:00 : ; ID=3 ; Strategy_Update=v11.0.785


There was a strategy update based on the autoupdater log, but freqtrade running did not update automatically the strategy version based on the freqtrade log. So then I manually stopped freqtrade and restarted. Then the freqtrade was running and the log showed the updated strategy version: 11.0.785

I've added many echo statements now to output to the autoupdater log to see the script process for identifying any issues during new updates.

Any suggestions on how to debug?

**Comment by GRrHaG** [comment]
Your strategy in your strategy path was updated from v11.0.700 to v11.0.785 but freqtrade did not take it into consideration except when you restarted manually?

**Comment by t3ch9** [comment]
Correct, After the autoupdater log showed the strategy update, I checked the freqtrade log which showed the old strategy version. After I manually stopped and restarted freqtrade, the strategy version in the freqtrade log showed the updated strategy version.

**Comment by GRrHaG** [comment]
when you restart manually do you use the same command : 
stop : pkill -f "/home/user/miniconda3/bin/python /home/user/miniconda3/bin/freqtrade trade --config configs/config_BOT1.json"
Start : freqtrade trade --config configs/config_BOT1.json

**Comment by t3ch9** [comment]
I dont recall whether I stopped freqtrade with CTRL+C or pkill, but to restart I did use freqtrade trade --config configs/config_BOT1.json

On the next strategy update I will use the pkill and report back to you.

**Comment by GRrHaG** [comment]
If you want debug you don't have to wait for the next update.
You can copy/paste old NFIX version  in your strategy path and delete last strategy update in history_autoupdater.txt

**Comment by t3ch9** [comment]
There was a strategy update today, here is the log (I added more echo statements to output to the log for debugging):

2022-05-17 16:30 : Latest Strategy v11.0.785 already install
2022-05-17 16:30 : Update FREQTRADE : allow
2022-05-17 16:35 : Create New Folder for Download Latest Strategy v11.0.830
2022-05-17 16:35 : Download Latest Strategy v11.0.830
2022-05-17 16:35 : Strategy : Updated
2022-05-17 16:35 : ; ID=12 ; Strategy_Update=v11.0.830
2022-05-17 16:35 : Pairlist : Updated
2022-05-17 16:35 : Blacklist Detail: Allow
2022-05-17 16:35 : Blacklist : Updated
2022-05-17 16:35 : FREQTARDE : Reload has been completed!
2022-05-17 16:35 : Update FREQTRADE : allow
2022-05-17 16:40 : Latest Strategy v11.0.830 already install


I haven't done anything since the strategy update. The same issue persists with Freqtrade log showing the old strategy running. 

2022-05-17 17:58:29,451 - freqtrade.worker - INFO - Bot heartbeat. PID=20433, version='2022.4.2, strategy_version: v11.0.785', state='RUNNING'
2022-05-17 17:59:29,504 - freqtrade.worker - INFO - Bot heartbeat. PID=20433, version='2022.4.2, strategy_version: v11.0.785', state='RUNNING'
2022-05-17 18:02:19,749 - freqtrade.worker - INFO - Bot heartbeat. PID=20433, version='2022.4.2, strategy_version: v11.0.785', state='RUNNING

**Comment by t3ch9** [comment]
I think I identified the problem, the command to stop Freqtrade was formatted incorrectly within the quotation marks. Will continue to debug.

**Comment by GRrHaG** [comment]
she was formatted incorrectly in config file or script dont take she corectly ?

**Comment by t3ch9** [comment]
yes, formatted incorrectly on config script. I corrected the config script, but strategy still not updated. I started line by line debugging.  This line sometimes does not return any value:

strategy_version=$(curl -s ${URL_GIT_STRATEGY} | grep -o '"tag_name": ".*"' | sed 's/"tag_name": "//' | sed 's/"//')

URL_GIT_STRATEGY returns: https://api.github.com/repos/iterativv/NostalgiaForInfinity/releases/latest
which looks correct. 

I will continue debugging.

**Comment by t3ch9** [comment]
Also seeing the following in the history log:

2022-05-19 02:50 : ; ID=1 ; ERROR=Strategy Latest Version is empty
2022-05-19 02:50 : Update FREQTRADE : allow
2022-05-19 02:55 : ; ID=1 ; ERROR=Strategy Latest Version is empty
2022-05-19 02:55 : Update FREQTRADE : allow
2022-05-19 03:00 : Latest Strategy v11.0.846 already install
2022-05-19 03:00 : Update FREQTRADE : allow
2022-05-19 03:05 : Latest Strategy v11.0.846 already install
2022-05-19 03:05 : Update FREQTRADE : allow


I checked the DOWNLOAD_STRATEGY_PATH folder and the latest strategy v11.0.846 is not there. 
Also the strategy file in the freqtrade user strategy folder is not updated.

**Comment by GRrHaG** [comment]
ERROR=Strategy Latest Version is empty : 
This error depend of github api rate limit :
- in normal condition if you run script with 5 minutes delay you have less than 10 errors per day (3.5% of errors per day )
- if you manually debug and run the script (less than 5 minutes), you exceed the github rate limit and have to wait a while before you can make a new request

**Comment by GRrHaG** [comment]
> Also seeing the following in the history log:
> 
> 2022-05-19 02:50 : ; ID=1 ; ERROR=Strategy Latest Version is empty 2022-05-19 02:50 : Update FREQTRADE : allow 2022-05-19 02:55 : ; ID=1 ; ERROR=Strategy Latest Version is empty 2022-05-19 02:55 : Update FREQTRADE : allow 2022-05-19 03:00 : Latest Strategy v11.0.846 already install 2022-05-19 03:00 : Update FREQTRADE : allow 2022-05-19 03:05 : Latest Strategy v11.0.846 already install 2022-05-19 03:05 : Update FREQTRADE : allow
> 
> I checked the DOWNLOAD_STRATEGY_PATH folder and the latest strategy v11.0.846 is not there. Also the strategy file in the freqtrade user strategy folder is not updated.

When the script updating freqtrade, it checks to be sure that freqtarde is up to date before entering the information in the history_autoupdater.txt
When it updates the strategy it does not do this check
There was surely a problem during the update, as he entered the information in the history_autoupdater.txt he assumes that it is up to date

Delete line Strategy_Update=v11.0.846 in history_autoupdater.txt for try to update 

Maybe i can add a check for strategy

**Comment by t3ch9** [comment]
I changed the cron to 10 minutes and I deleted all the lines in history_autoupdater.txt with  Strategy_Update=v11.0.846 

The log shows:

2022-05-19 18:10 : ; ID=1 ; ERROR=Strategy Latest Version is empty
2022-05-19 18:10 : Update FREQTRADE : allow
2022-05-19 18:15 : ; ID=1 ; ERROR=Strategy Latest Version is empty
2022-05-19 18:15 : Update FREQTRADE : allow
2022-05-19 18:20 : ; ID=1 ; ERROR=Strategy Latest Version is empty
2022-05-19 18:20 : Update FREQTRADE : allow
2022-05-19 18:30 : Latest Strategy v11.0.846 already install
2022-05-19 18:30 : Update FREQTRADE : allow


Both the DOWNLOAD_STRATEGY_PATH folder and the strategy file running have not updated.

**Comment by GRrHaG** [comment]
6 days ago your script could download the latest version of the strategy but now it doesn't.

you can add : " >> [yourpath] 2>&1" at the end of your crontab line for make a log file to help you to debug
(ex :  */5 * * * * bash -lc /home/pi/ft_userdata/tools/GRrHaG_AutoUpdater.sh >> /home/pi/ft_userdata/tools/file 2>&1)

Do you change your DOWNLOAD_STRATEGY_PATH ? 
Or do you change the name of the script without doing a "chmod +x" again?

**Comment by t3ch9** [comment]
I found the issues. Strategy update is working properly. Thank you for your help!!

**Comment by GRrHaG** [comment]
Good news ! Well done !
